// <auto-generated />
using System;
using EngineeringManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngineeringManagement.Data.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20240830181354_AddGeneralEmployeesTable")]
    partial class AddGeneralEmployeesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("EngineeringManagement.Data.Models.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CertificationName = "Espacios Confinados"
                        },
                        new
                        {
                            Id = -2,
                            CertificationName = "Corte y Soldadura"
                        },
                        new
                        {
                            Id = -3,
                            CertificationName = "NOM-009-STPS-2011",
                            Description = "Trabajos en Altura"
                        },
                        new
                        {
                            Id = -4,
                            CertificationName = "NOM-005-STPS-1999",
                            Description = "Condiciones de Seguridad e Higiene en los centros de trabajo para el manejo, transporte y almacenamiento de sustancias quimicas peligrosas"
                        },
                        new
                        {
                            Id = -5,
                            CertificationName = "NOM-018-STPS-2015",
                            Description = "Sistema Globalmente Armonizado para la identificacion y comunicación de peligros y riesgos por sustancias quimicas peligrosas en los centros de trabajo"
                        },
                        new
                        {
                            Id = -6,
                            CertificationName = "NOM-029-STPS-2011",
                            Description = "Mantenimiento de las instalaciones Electricas en los Centros de Trabajo"
                        },
                        new
                        {
                            Id = -7,
                            CertificationName = "NOM-028-STPS-2012",
                            Description = "(Organización del trabajo-Seguridad en los procesos y equipos que manejen sustancias quimicas) Apertura de lineas de proceso."
                        },
                        new
                        {
                            Id = -8,
                            CertificationName = "NOM-004-STPS-1999",
                            Description = "Sistemas de Proteccion y Diapositivos de Seguridad en la Maquinaria y Equipo (candados y etiquetas)"
                        },
                        new
                        {
                            Id = -9,
                            CertificationName = "Combate de Incendios con Extintores"
                        },
                        new
                        {
                            Id = -10,
                            CertificationName = "NOM-002-STPS-2010",
                            Description = "Condiciones de Seguridad Prevencion y Proteccion contra Incendio en los centros de Trabajo"
                        },
                        new
                        {
                            Id = -11,
                            CertificationName = "NOM-017- STPS-2008",
                            Description = "Equipo de proteccion personal Selección uso y manejo en los centros de trabajo"
                        },
                        new
                        {
                            Id = -12,
                            CertificationName = "NOM-026-STPS-2008",
                            Description = "Colores y señales de seguridad e higiene e identificacion de riesgos conducidas por tuberias"
                        },
                        new
                        {
                            Id = -13,
                            CertificationName = "Primeros Auxilios"
                        },
                        new
                        {
                            Id = -14,
                            CertificationName = "Formacion de Armadores de Andamios"
                        },
                        new
                        {
                            Id = -15,
                            CertificationName = "Izajes y Cargas"
                        },
                        new
                        {
                            Id = -16,
                            CertificationName = "Operación segura de plataformas articuladas y elevadas"
                        },
                        new
                        {
                            Id = -17,
                            CertificationName = "NOM-031",
                            Description = "Condiciones de seguridad e higiene"
                        },
                        new
                        {
                            Id = -18,
                            CertificationName = "Uso, revisión, reposición, limpieza, limitaciones, mantenimiento, resguardo y disposición final del equipo de protección personal."
                        },
                        new
                        {
                            Id = -19,
                            CertificationName = "NOM-036",
                            Description = "Manejo de cargas manuales"
                        },
                        new
                        {
                            Id = -20,
                            CertificationName = "NOM-030",
                            Description = "Servicios Preventivos de Seguridad y Salud en el Trabajo"
                        },
                        new
                        {
                            Id = -21,
                            CertificationName = "Trabajos en caliente"
                        },
                        new
                        {
                            Id = -22,
                            CertificationName = "Aperturas de líneas de proceso"
                        },
                        new
                        {
                            Id = -23,
                            CertificationName = "Candados y etiquetas"
                        },
                        new
                        {
                            Id = -24,
                            CertificationName = "NOM-026",
                            Description = "CORRECTA INTERPRETACION DE LOS ELEMENTOS DE SEÑALIZACION DEL CENTRO DE TRABAJO"
                        },
                        new
                        {
                            Id = -25,
                            CertificationName = "NOM-029",
                            Description = "MANTENIMIENTO DE LAS INSTALACIONES ELECTRICAS EN LOS CENTROS DE TRABAJO"
                        });
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabsFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SisositFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            EmployeeName = "Aguilar Gonzalez Armando",
                            EmployeeType = 2,
                            Position = "Electrico"
                        },
                        new
                        {
                            Id = -2,
                            EmployeeName = "Alejandre Blanco Javier",
                            EmployeeType = 2,
                            Position = "Electrico"
                        },
                        new
                        {
                            Id = -3,
                            EmployeeName = "Alfaro Muñiz Margarito",
                            EmployeeType = 1,
                            Position = "Especialista en Tuberias"
                        },
                        new
                        {
                            Id = -4,
                            EmployeeName = "Angeles Hernandez Jesus",
                            EmployeeType = 2,
                            Position = "Ayudante General"
                        },
                        new
                        {
                            Id = -5,
                            EmployeeName = "Camacho Aguilar Ricardo",
                            EmployeeType = 1,
                            Position = "Especialista A en Instrumentacion"
                        },
                        new
                        {
                            Id = -6,
                            EmployeeName = "Campos Medina Axel",
                            EmployeeType = 2,
                            Position = "Ayudante General"
                        },
                        new
                        {
                            Id = -7,
                            EmployeeName = "Cardenas Vargas Carlos",
                            EmployeeType = 2,
                            Position = "Jefe de Ingenieria de Confiabilidad"
                        },
                        new
                        {
                            Id = -8,
                            EmployeeName = "Cartagena Vicencio Diego Alberto",
                            EmployeeType = 1,
                            Position = "Controlador de Proyectos Jr"
                        },
                        new
                        {
                            Id = -9,
                            EmployeeName = "Cisneros Zuñiga Gustavo",
                            EmployeeType = 2,
                            Position = "Electrico"
                        },
                        new
                        {
                            Id = -10,
                            EmployeeName = "De La Cruz Mendoza Andres",
                            EmployeeType = 1,
                            Position = "Ingeniero b civil y estructuras"
                        },
                        new
                        {
                            Id = -11,
                            EmployeeName = "Del Angel Del Angel Javier",
                            EmployeeType = 1,
                            Position = "Supervisor de Calidad"
                        },
                        new
                        {
                            Id = -12,
                            EmployeeName = "Diaz Rendon Audrey Daniela",
                            EmployeeType = 1,
                            Position = "Cadista Jr"
                        },
                        new
                        {
                            Id = -13,
                            EmployeeName = "Diaz Rendon Wendy Montserrat",
                            EmployeeType = 2,
                            Position = "Control de documentos"
                        },
                        new
                        {
                            Id = -14,
                            EmployeeName = "Gaspar Flores Jose Ernesto",
                            EmployeeType = 1,
                            Position = "Ingeniero A de Tuberias"
                        },
                        new
                        {
                            Id = -15,
                            EmployeeName = "Gomez Reyes Edwin De Jesus",
                            EmployeeType = 2,
                            Position = "Cadista Jr"
                        },
                        new
                        {
                            Id = -16,
                            EmployeeName = "Hernandez Valdez Joel",
                            EmployeeType = 2,
                            Position = "Cabo Electrico"
                        },
                        new
                        {
                            Id = -17,
                            EmployeeName = "Herrera Arteaga Josue",
                            EmployeeType = 1,
                            Position = "Ingeniero A de Tuberias"
                        },
                        new
                        {
                            Id = -18,
                            EmployeeName = "Hervert Garibay Ricardo de Jesus",
                            EmployeeType = 2,
                            Position = "Ayudante General"
                        },
                        new
                        {
                            Id = -19,
                            EmployeeName = "Juarez Lopez Guillermo",
                            EmployeeType = 2,
                            Position = "Supervisor de disciplina"
                        },
                        new
                        {
                            Id = -20,
                            EmployeeName = "Juarez Lopez Leonardo Alejandro",
                            EmployeeType = 2,
                            Position = "Supervisor de disciplina"
                        },
                        new
                        {
                            Id = -21,
                            EmployeeName = "Lopez Ochoa Jonathan",
                            EmployeeType = 2,
                            Position = "Electrico"
                        },
                        new
                        {
                            Id = -22,
                            EmployeeName = "Lopez Pacheco Javier",
                            EmployeeType = 2,
                            Position = "Coordinador Electrico e Instrumentacion"
                        },
                        new
                        {
                            Id = -23,
                            EmployeeName = "Martinez Baeza Francisco",
                            EmployeeType = 2,
                            Position = "Auxiliar de control de proyectos"
                        },
                        new
                        {
                            Id = -24,
                            EmployeeName = "Maya Peña Juan Francisco",
                            EmployeeType = 1,
                            Position = "Jefe de ingenieria"
                        },
                        new
                        {
                            Id = -25,
                            EmployeeName = "Melo Rivera Juan Jesus",
                            EmployeeType = 2,
                            Position = "Ayudante General"
                        },
                        new
                        {
                            Id = -26,
                            EmployeeName = "Miranda Martinez Andrea",
                            EmployeeType = 2,
                            Position = "Ingeniero en procesos c"
                        },
                        new
                        {
                            Id = -27,
                            EmployeeName = "Nava Comsille Arturo",
                            EmployeeType = 1,
                            Position = "Jefe de Ingenieria"
                        },
                        new
                        {
                            Id = -28,
                            EmployeeName = "Osorio Estrella Hector",
                            EmployeeType = 2,
                            Position = "Analista de precios unitarios"
                        },
                        new
                        {
                            Id = -29,
                            EmployeeName = "Otero Gonzalez Irma Jessica",
                            EmployeeType = 1,
                            Position = "Ingeniero C de Proceso"
                        },
                        new
                        {
                            Id = -30,
                            EmployeeName = "Piñeyro Lara Sergio Israel",
                            EmployeeType = 2,
                            Position = "Gerente de Ingenieria"
                        },
                        new
                        {
                            Id = -31,
                            EmployeeName = "Ramirez Francisco Jonathan",
                            EmployeeType = 1,
                            Position = "Cadista Jr"
                        },
                        new
                        {
                            Id = -32,
                            EmployeeName = "Ramirez Francisco Luis Enrique",
                            EmployeeType = 1,
                            Position = "Proyectista"
                        },
                        new
                        {
                            Id = -33,
                            EmployeeName = "Ramos Ruiz Alberto Ivan",
                            EmployeeType = 1,
                            Position = "Control de Materiales"
                        },
                        new
                        {
                            Id = -34,
                            EmployeeName = "Rodriguez Guerrero Jose Martin",
                            EmployeeType = 2,
                            Position = "Electrico"
                        },
                        new
                        {
                            Id = -35,
                            EmployeeName = "Sanchez Mar Nelson Ivan",
                            EmployeeType = 2,
                            Position = "Ayudante General"
                        },
                        new
                        {
                            Id = -36,
                            EmployeeName = "Saucedo Ramirez Fernando",
                            EmployeeType = 2,
                            Position = "Andamiero"
                        },
                        new
                        {
                            Id = -37,
                            EmployeeName = "Saucedo Ramirez Fernando",
                            EmployeeType = 2,
                            Position = "Ayudante General"
                        },
                        new
                        {
                            Id = -38,
                            EmployeeName = "Villanueva Espinoza Julio Cesar",
                            EmployeeType = 1,
                            Position = "Ingeniero A Electrico"
                        },
                        new
                        {
                            Id = -39,
                            EmployeeName = "Santiago Hernandez Bernabe Esequiel",
                            EmployeeType = 2,
                            Position = "Electrico"
                        },
                        new
                        {
                            Id = -40,
                            EmployeeName = "Alvarez Martir Christian",
                            EmployeeType = 1,
                            Position = "Auxiliar de control de proyectos"
                        });
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.EmployeeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCertifications");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CertificationId = -1,
                            EmployeeId = -1,
                            EndDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -2,
                            CertificationId = -2,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -3,
                            CertificationId = -3,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -4,
                            CertificationId = -4,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -5,
                            CertificationId = -5,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -6,
                            CertificationId = -6,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -7,
                            CertificationId = -7,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -8,
                            CertificationId = -8,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -9,
                            CertificationId = -9,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -10,
                            CertificationId = -17,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -11,
                            CertificationId = -18,
                            EmployeeId = -1,
                            EndDate = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -12,
                            CertificationId = -1,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -13,
                            CertificationId = -2,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -14,
                            CertificationId = -3,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -15,
                            CertificationId = -4,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -16,
                            CertificationId = -5,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -17,
                            CertificationId = -6,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -18,
                            CertificationId = -7,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -19,
                            CertificationId = -8,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -20,
                            CertificationId = -9,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -21,
                            CertificationId = -11,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -22,
                            CertificationId = -12,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -23,
                            CertificationId = -17,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -24,
                            CertificationId = -19,
                            EmployeeId = -2,
                            EndDate = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -25,
                            CertificationId = -1,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -26,
                            CertificationId = -2,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -27,
                            CertificationId = -3,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -28,
                            CertificationId = -4,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -29,
                            CertificationId = -5,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -30,
                            CertificationId = -6,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -31,
                            CertificationId = -7,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -32,
                            CertificationId = -8,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -33,
                            CertificationId = -9,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -34,
                            CertificationId = -10,
                            EmployeeId = -3,
                            EndDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -35,
                            CertificationId = -11,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -36,
                            CertificationId = -12,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -37,
                            CertificationId = -14,
                            EmployeeId = -3,
                            EndDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -38,
                            CertificationId = -16,
                            EmployeeId = -3,
                            EndDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -39,
                            CertificationId = -1,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -40,
                            CertificationId = -2,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -41,
                            CertificationId = -3,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -42,
                            CertificationId = -4,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -43,
                            CertificationId = -5,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -44,
                            CertificationId = -6,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -45,
                            CertificationId = -7,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -46,
                            CertificationId = -8,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -47,
                            CertificationId = -9,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -48,
                            CertificationId = -10,
                            EmployeeId = -5,
                            EndDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -49,
                            CertificationId = -11,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -50,
                            CertificationId = -12,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -51,
                            CertificationId = -14,
                            EmployeeId = -5,
                            EndDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -52,
                            CertificationId = -16,
                            EmployeeId = -5,
                            EndDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -53,
                            CertificationId = -1,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -54,
                            CertificationId = -2,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -55,
                            CertificationId = -3,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -56,
                            CertificationId = -4,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -57,
                            CertificationId = -5,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -58,
                            CertificationId = -6,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -59,
                            CertificationId = -7,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -60,
                            CertificationId = -8,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -61,
                            CertificationId = -9,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -62,
                            CertificationId = -11,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -63,
                            CertificationId = -12,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -64,
                            CertificationId = -16,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -65,
                            CertificationId = -17,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -66,
                            CertificationId = -20,
                            EmployeeId = -6,
                            EndDate = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -67,
                            CertificationId = -1,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -68,
                            CertificationId = -2,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -69,
                            CertificationId = -3,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -70,
                            CertificationId = -4,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -71,
                            CertificationId = -5,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -72,
                            CertificationId = -6,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -73,
                            CertificationId = -7,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -74,
                            CertificationId = -8,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -75,
                            CertificationId = -9,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -76,
                            CertificationId = -11,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -77,
                            CertificationId = -12,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -78,
                            CertificationId = -16,
                            EmployeeId = -8,
                            EndDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -79,
                            CertificationId = -1,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -80,
                            CertificationId = -2,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -81,
                            CertificationId = -3,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -82,
                            CertificationId = -4,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -83,
                            CertificationId = -5,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -84,
                            CertificationId = -6,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -85,
                            CertificationId = -7,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -86,
                            CertificationId = -8,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -87,
                            CertificationId = -9,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -88,
                            CertificationId = -10,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -89,
                            CertificationId = -11,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -90,
                            CertificationId = -12,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -91,
                            CertificationId = -17,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -92,
                            CertificationId = -20,
                            EmployeeId = -9,
                            EndDate = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -93,
                            CertificationId = -1,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -94,
                            CertificationId = -2,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -95,
                            CertificationId = -3,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -96,
                            CertificationId = -4,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -97,
                            CertificationId = -5,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -98,
                            CertificationId = -6,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -99,
                            CertificationId = -7,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -100,
                            CertificationId = -8,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -101,
                            CertificationId = -9,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -102,
                            CertificationId = -10,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -103,
                            CertificationId = -11,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -104,
                            CertificationId = -12,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -105,
                            CertificationId = -15,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = -106,
                            CertificationId = -16,
                            EmployeeId = -10,
                            EndDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.EmployeeMedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Able")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeMedFiles");
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacilityName")
                        .IsUnique()
                        .HasDatabaseName("UQ_FacilityName");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FacilityName = "Sabic"
                        },
                        new
                        {
                            Id = -2,
                            FacilityName = "Cabot"
                        });
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.FacilityCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("FacilityId");

                    b.ToTable("FacilityCertifications");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CertificationId = -2,
                            FacilityId = -1
                        },
                        new
                        {
                            Id = -2,
                            CertificationId = -9,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -3,
                            CertificationId = -10,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -4,
                            CertificationId = -11,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -5,
                            CertificationId = -12,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -6,
                            CertificationId = -13,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -7,
                            CertificationId = -14,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -8,
                            CertificationId = -15,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -9,
                            CertificationId = -16,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -10,
                            CertificationId = -17,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -11,
                            CertificationId = -1,
                            FacilityId = -1
                        },
                        new
                        {
                            Id = -12,
                            CertificationId = -1,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -13,
                            CertificationId = -3,
                            FacilityId = -1
                        },
                        new
                        {
                            Id = -14,
                            CertificationId = -3,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -15,
                            CertificationId = -4,
                            FacilityId = -1
                        },
                        new
                        {
                            Id = -16,
                            CertificationId = -4,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -17,
                            CertificationId = -5,
                            FacilityId = -1
                        },
                        new
                        {
                            Id = -18,
                            CertificationId = -5,
                            FacilityId = -2
                        },
                        new
                        {
                            Id = -19,
                            CertificationId = -6,
                            FacilityId = -1
                        },
                        new
                        {
                            Id = -20,
                            CertificationId = -6,
                            FacilityId = -2
                        });
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.GeneralEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Curp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelationShip")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Has2Pictures")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Has2RecomendationLetters")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasBankStatement")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCellPhone")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasComputer")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCurp")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasDrivingLicense")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasEquipment")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasInfonavit")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasJobReferences")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasNss")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasProofOfAddress")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasProofOfStudies")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSat")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasUniforms")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasVotingCard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalCellPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rfc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkCellPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralEmployees");
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.EmployeeCertification", b =>
                {
                    b.HasOne("EngineeringManagement.Data.Models.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineeringManagement.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.EmployeeMedFile", b =>
                {
                    b.HasOne("EngineeringManagement.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EngineeringManagement.Data.Models.FacilityCertification", b =>
                {
                    b.HasOne("EngineeringManagement.Data.Models.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineeringManagement.Data.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Facility");
                });
#pragma warning restore 612, 618
        }
    }
}
