name: Build Control Total Ingenieria

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish_output

      - name: Install 7-Zip
        run: choco install 7zip

      - name: Zip published files
        run: |
          7z a -tzip ./ControlTotalIngenieria.zip ./publish_output\* -x!*.pdb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ControlTotalIngenieria
          path: ./ControlTotalIngenieria.zip

      - name: Clean up
        run: |
          Remove-Item -Path ./publish_output -Recurse -Force
