name: Build and Upload .NET WinForms Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish_output

      - name: Zip published files
        run: Compress-Archive -Path ./publish_output/* -DestinationPath ./ControlTotalIngenieria.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ControlTotalIngenieria
          path: ./ControlTotalIngenieria.zip
